// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aZpqwzEqMU83o5JsBEvwHw
// Component: JWuSu6KynG
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: aZpqwzEqMU83o5JsBEvwHw/projectcss
import * as sty from "./PlasmicParagraph.module.css"; // plasmic-import: JWuSu6KynG/css

export type PlasmicParagraph__VariantMembers = {};

export type PlasmicParagraph__VariantsArgs = {};
type VariantPropType = keyof PlasmicParagraph__VariantsArgs;
export const PlasmicParagraph__VariantProps = new Array<VariantPropType>();

export type PlasmicParagraph__ArgsType = {};
type ArgPropType = keyof PlasmicParagraph__ArgsType;
export const PlasmicParagraph__ArgProps = new Array<ArgPropType>();

export type PlasmicParagraph__OverridesType = {
  root?: p.Flex<"div">;
  box?: p.Flex<"div">;
};

export interface DefaultParagraphProps {
  className?: string;
}

function PlasmicParagraph__RenderFunc(props: {
  variants: PlasmicParagraph__VariantsArgs;
  args: PlasmicParagraph__ArgsType;
  overrides: PlasmicParagraph__OverridesType;
  dataFetches?: PlasmicParagraph__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, defaultcss.__wab_text, sty.box)}
      >
        {"Enter some text"}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  box: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicParagraph__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicParagraph__VariantsArgs;
    args?: PlasmicParagraph__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicParagraph__Fetches;
  } & Omit<PlasmicParagraph__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicParagraph__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicParagraph__ArgProps,
      internalVariantPropNames: PlasmicParagraph__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicParagraph__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicParagraph";
  } else {
    func.displayName = `PlasmicParagraph.${nodeName}`;
  }
  return func;
}

export const PlasmicParagraph = Object.assign(
  // Top-level PlasmicParagraph renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),

    // Metadata about props expected for PlasmicParagraph
    internalVariantProps: PlasmicParagraph__VariantProps,
    internalArgProps: PlasmicParagraph__ArgProps
  }
);

export default PlasmicParagraph;
/* prettier-ignore-end */
